In [64]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression , Lasso , Ridge
from sklearn.metrics import  r2_score , mean_absolute_error,mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [40]:
df = pd.read_csv("ship_fuel_efficiency.csv")
df.head()

,ship_id,ship_type,route_id,month,distance,fuel_type,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency
0,NG001,Oil Service Boat,Warri-Bonny,January,132.26,HFO,3779.77,10625.76,Stormy,92.14
1,NG001,Oil Service Boat,Port Harcourt-Lagos,February,128.52,HFO,4461.44,12779.73,Moderate,92.98
2,NG001,Oil Service Boat,Port Harcourt-Lagos,March,67.30,HFO,1867.73,5353.01,Calm,87.61
3,NG001,Oil Service Boat,Port Harcourt-Lagos,April,71.68,Diesel,2393.51,6506.52,Stormy,87.42
4,NG001,Oil Service Boat,Lagos-Apapa,May,134.32,HFO,4267.19,11617.03,Calm,85.61

In [41]:
df.tail()

,ship_id,ship_type,route_id,month,distance,fuel_type,fuel_consumption,CO2_emissions,weather_conditions,engine_efficiency
1435,NG120,Fishing Trawler,Port Harcourt-Lagos,August,63.84,Diesel,1633.85,4852.28,Stormy,75.88
1436,NG120,Fishing Trawler,Lagos-Apapa,September,61.43,HFO,1263.48,3571.13,Calm,78.00
1437,NG120,Fishing Trawler,Port Harcourt-Lagos,October,193.09,HFO,4661.63,12267.13,Stormy,79.67
1438,NG120,Fishing Trawler,Lagos-Apapa,November,166.50,Diesel,4298.00,12297.71,Moderate,92.87
1439,NG120,Fishing Trawler,Warri-Bonny,December,127.66,Diesel,3549.91,10641.90,Moderate,90.82

In [42]:
df.shape

(1440, 10)

In [43]:
df.columns

Index(['ship_id', 'ship_type', 'route_id', 'month', 'distance', 'fuel_type',
       'fuel_consumption', 'CO2_emissions', 'weather_conditions',
       'engine_efficiency'],
      dtype='str')

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ship_id             1440 non-null   str
 1   ship_type           1440 non-null   str
 2   route_id            1440 non-null   str
 3   month               1440 non-null   str
 4   distance            1440 non-null   float64
 5   fuel_type           1440 non-null   str
 6   fuel_consumption    1440 non-null   float64
 7   CO2_emissions       1440 non-null   float64
 8   weather_conditions  1440 non-null   str
 9   engine_efficiency   1440 non-null   float64
dtypes: float64(4), str(6)
memory usage: 112.6 KB

In [45]:
df.describe()

          distance  fuel_consumption  CO2_emissions  engine_efficiency
count  1440.000000       1440.000000    1440.000000        1440.000000
mean    151.753354       4844.246535   13365.454882          82.582924
std     108.472230       4892.352813   13567.650118           7.158289
min      20.080000        237.880000     615.680000          70.010000
25%      79.002500       1837.962500    4991.485000          76.255000
50%     123.465000       3060.880000    8423.255000          82.775000
75%     180.780000       4870.675000   13447.120000          88.862500
max     498.550000      24648.520000   71871.210000          94.980000

# Data Cleaning

In [46]:
df= df.drop(['CO2_emissions'],axis=1)
df = df.drop(['ship_id'],axis=1)

In [47]:
df.isna().sum()

ship_type             0
route_id              0
month                 0
distance              0
fuel_type             0
fuel_consumption      0
weather_conditions    0
engine_efficiency     0
dtype: int64

There is no nan values

In [48]:
df.duplicated().sum()

np.int64(0)

There is no duplicated values

# Data Spliting

In [49]:
x = df.drop(['fuel_consumption'],axis=1)
y = df[['fuel_consumption']]

In [50]:
x.head()

,ship_type,route_id,month,distance,fuel_type,weather_conditions,engine_efficiency
0,Oil Service Boat,Warri-Bonny,January,132.26,HFO,Stormy,92.14
1,Oil Service Boat,Port Harcourt-Lagos,February,128.52,HFO,Moderate,92.98
2,Oil Service Boat,Port Harcourt-Lagos,March,67.30,HFO,Calm,87.61
3,Oil Service Boat,Port Harcourt-Lagos,April,71.68,Diesel,Stormy,87.42
4,Oil Service Boat,Lagos-Apapa,May,134.32,HFO,Calm,85.61

# Applying Encoding

In [51]:
le = LabelEncoder()

In [52]:
cat_col = df.select_dtypes(include=[object]).columns

C:\Users\INTEL\AppData\Local\Temp\ipykernel_18016\2752859863.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col = df.select_dtypes(include=[object]).columns

In [53]:
for i in cat_col:
    x[i] = le.fit_transform(df[i])

# Model Implimentation

In [54]:
x_train,x_test,y_train,y_test= train_test_split(x,y,train_size=.8,random_state=42)

# Linear Regression Apply

In [55]:
lr = LinearRegression()


# Train Model
linear_model = lr.fit(x_train,y_train)
print("Training Score : ",linear_model.score(x_train,y_train))


# Test Model
print("Test Score : ",linear_model.score(x_test,y_test))

# Prediction 

pred = lr.predict(x_test)

Training Score :  0.9012799831153461
Test Score :  0.9134027453760544

# Model Evaluation

In [56]:
# MSE 
mse = mean_squared_error(y_test,pred)
print("MSE : ", mse)

mae = mean_absolute_error(y_test,pred)
print("MAE : ", mae)

r2 = r2_score(y_test ,pred )
print("R2_Score : ", r2)

MSE :  2330370.95930335
MAE :  1159.4751268542157
R2_Score :  0.9134027453760544

# Decision Tree Regressor Apply

In [57]:
dt = DecisionTreeRegressor()
# Model Training
model_dt = dt.fit(x_train,y_train)
print("Training Score : ", model_dt.score(x_train,y_train))
# Mode
print("Test Score : ", model_dt.score(x_test,y_test))

 # prediction
dt_pred =dt.predict(x_test)

Training Score :  1.0
Test Score :  0.9270503816920364

# Model Evaluation

In [58]:
# MSE 
mse = mean_squared_error(y_test,dt_pred)
print("MSE : ", mse)

mae = mean_absolute_error(y_test,dt_pred)
print("MAE : ", mae)

r2 = r2_score(y_test ,dt_pred )
print("R2_Score : ", r2)

MSE :  1963106.9453111114
MAE :  804.3304861111111
R2_Score :  0.9270503816920364

# Lasso Regression

In [59]:
ls = Lasso()

In [60]:
# training Model 

model_ls= ls.fit(x_train,y_train)
print("Training Score : ", model_ls.score(x_train,y_train))

# Test Model 
print("Test Data : ", model_ls.score(x_test,y_test))

# prediction

ls_pred = ls.predict(x_test)

Training Score :  0.9012796292536809
Test Data :  0.9134163574104027

#  Lesso Model Evaluation

In [61]:
# MSE 
mse = mean_squared_error(y_test,ls_pred)
print("MSE : ", mse)

mae = mean_absolute_error(y_test,ls_pred)
print("MAE : ", mae)

r2 = r2_score(y_test ,ls_pred )
print("R2_Score : ", r2)

MSE :  2330004.6533542736
MAE :  1159.4529413343491
R2_Score :  0.9134163574104027

# Ridge

In [65]:
rd = Ridge()

In [66]:
# training Model 

model_rd= rd.fit(x_train,y_train)
print("Training Score : ", model_rd.score(x_train,y_train))

# Test Model 
print("Test Data : ", model_rd.score(x_test,y_test))

# prediction

rd_pred = rd.predict(x_test)

Training Score :  0.9012799139072182
Test Data :  0.9134041563851493

# Model Evaluation

In [67]:
# MSE 
mse = mean_squared_error(y_test,rd_pred)
print("MSE : ", mse)

mae = mean_absolute_error(y_test,rd_pred)
print("MAE : ", mae)

r2 = r2_score(y_test ,rd_pred )
print("R2_Score : ", r2)

MSE :  2330332.988415793
MAE :  1159.4775965375957
R2_Score :  0.9134041563851493

In [68]:
import seaborn as sns 
import matplotlib.pyplot as plt